apiVersion: v1
kind: Deployment
metadata:
  name: depl1
  namespace: lesson14
  labels:
    app: goapp
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: web
        image: 
        ports:
        - containerPort: 8080 

