apiVersion: v1
kind: Service
metadata: 
  name: my-service
  namespace: lesson14
spec:  
  selector:
    app: goapp 
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 30050
    targetPort: 80
    protocol: TCP

